Codegeneration Array
cs-24-sw-4-03/P4-ParserGenerator pull request #90
Opened 2024-05-04 16:53 UTC by Peterrahr

2024-05-05 10:58 UTC, od45pv commented
Andreas har lavet om på måden vi tilføjer ting til vores stringbuilder, output og imports. Vi skal derfor lige være sikrer på, hvordan vi får det korrekt ind i Codegeneration.

2024-05-05 10:59 UTC, od45pv commented
@Peterrahr Fikser du selv conflicts?

2024-05-06 06:36 UTC, EmilChri requested changes

2024-05-06 06:36 UTC, EmilChri commented on generator/src/main/antlr4/org/abcd/examples/ParLang/ParLang.g4
> +printBody : (identifier | STRING | arrayAccess) (PLUS (identifier | STRING ))*;
bør være det her:

printBody : (STRING | identifier ) (PLUS (STRING | identifier))*

2024-05-06 11:44 UTC, Andreas272 approved these changes

2024-05-06 11:44 UTC, merged